[package]
name = "koharu"
version.workspace = true
edition.workspace = true
description.workspace = true
license-file.workspace = true
authors.workspace = true
readme.workspace = true
homepage.workspace = true
repository.workspace = true
keywords.workspace = true

[dependencies]
comic-text-detector = { workspace = true }
manga-ocr = { workspace = true }
lama = { workspace = true }
llm = { workspace = true }
anyhow = { workspace = true }
ort = { workspace = true }
rfd = { workspace = true }
open = { workspace = true }
serde = { workspace = true }
serde_bytes = { workspace = true }
serde_json = { workspace = true }
image = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
postcard = { workspace = true }
thiserror = { workspace = true }
tauri = { workspace = true }
blake3 = { workspace = true }
lru = { workspace = true }
tokio = { workspace = true }
rayon = { workspace = true }
imageproc = { workspace = true }
strum = { workspace = true }
hf-hub = { workspace = true }
cuda-rt = { workspace = true, optional = true }
velopack = { workspace = true, optional = true }

[features]
cuda = [
    "ort/cuda",
    "comic-text-detector/cuda",
    "manga-ocr/cuda",
    "lama/cuda",
    "llm/cuda",
    "cuda-rt",
]
bundle = ["velopack"]

[build-dependencies]
tauri-build = { workspace = true }
