[package]
name = "koharu"
version.workspace = true
edition.workspace = true
description.workspace = true
license-file.workspace = true
authors.workspace = true
readme.workspace = true
homepage.workspace = true
repository.workspace = true
keywords.workspace = true
include = [
    "src/**",
    "icons/**",
    "gen/**",
    "tauri.conf.json",
    "tauri.*.conf.json",
    "capabilities/**",
    "build.rs",
    "../ui/out/**",
]

[dependencies]
koharu-core = { workspace = true }
koharu-runtime = { workspace = true }
koharu-models = { workspace = true }
koharu-renderer = { workspace = true }
anyhow = { workspace = true }
ort = { workspace = true }
rfd = { workspace = true }
open = { workspace = true }
serde = { workspace = true }
serde_bytes = { workspace = true }
serde_json = { workspace = true }
image = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
postcard = { workspace = true }
thiserror = { workspace = true }
tauri = { workspace = true }
blake3 = { workspace = true }
tokio = { workspace = true }
rayon = { workspace = true }
imageproc = { workspace = true }
strum = { workspace = true }
hf-hub = { workspace = true }
velopack = { workspace = true, optional = true }
dirs = { workspace = true }
unicode-script = { workspace = true }

[features]
default = ["koharu-runtime/onnxruntime"]
cuda = ["ort/cuda", "koharu-models/cuda", "koharu-runtime/cuda"]
bundle = ["velopack"]

[build-dependencies]
tauri-build = { workspace = true }
