[package]
name = "cuda-rt"
version.workspace = true
edition.workspace = true
description.workspace = true
license-file.workspace = true
authors.workspace = true
readme.workspace = true
homepage.workspace = true
repository.workspace = true
keywords.workspace = true

[dependencies]

[build-dependencies]
anyhow = { workspace = true }
ureq = { workspace = true }
serde_json = { workspace = true }
zip = { workspace = true }
