[package]
name = "koharu-renderer"
version.workspace = true
edition.workspace = true
description.workspace = true
license-file.workspace = true
authors.workspace = true
readme.workspace = true
homepage.workspace = true
repository.workspace = true
keywords.workspace = true

[dependencies]
swash = { workspace = true }
fontdb = { workspace = true }
anyhow = { workspace = true }
ndarray = { workspace = true }
image = { workspace = true }
unicode-linebreak = { workspace = true }
rayon = { workspace = true }
