[env]
# refer: https://stackoverflow.com/questions/43577885/is-there-a-cargo-environment-variable-for-the-workspace-directory
CARGO_WORKSPACE_DIR = { value = "", relative = true }
# CUDA 13.1 requires C++17
NVCC_PREPEND_FLAGS = "-std=c++17"
