[env]
# refer: https://stackoverflow.com/questions/43577885/is-there-a-cargo-environment-variable-for-the-workspace-directory
CARGO_WORKSPACE_DIR = { value = "", relative = true }
# Use the dynamic runtime for MSVC builds
CFLAGS_x86_64-pc-windows-msvc = "/MD"
CXXFLAGS_x86_64-pc-windows-msvc = "/MD"
