[package]
name = "koharu-rpc"
version.workspace = true
edition.workspace = true
description.workspace = true
authors.workspace = true
publish.workspace = true

[dependencies]
koharu-http = { workspace = true }
koharu-pipeline = { workspace = true }
anyhow = { workspace = true }
axum = { workspace = true }
futures = { workspace = true }
rmp-serde = { workspace = true }
rmpv = { workspace = true }
serde = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
